import React from 'react'
import FAQ from './FAQ'
import Blog from './Blog'
import ProductCategories from './ProductCategories'
import PasswordReset from './PasswordReset'
import ForgotPassword from './ForgotPassword'
import OrderTracking from './OrderTracking'
import Wishlist from './Wishlist'
import SearchResults from './SearchResults'
import Contact from './Contact'
import OrderConfirmation from './OrderConfirmation'
import UserDashboard from './UserDashboard'
import Register from './Register'
import Login from './Login'
import Checkout from './Checkout'
import About from './About'
import Cart from './Cart'
import ProductDetails from './ProductDetails'
import Products from './Products'
import Invoice from './Invoice'

export default { FAQ, Blog, ProductCategories, PasswordReset, ForgotPassword, OrderTracking, Wishlist, SearchResults, Contact, OrderConfirmation, UserDashboard, Register, Login, Checkout, About, Cart, ProductDetails, Products, Invoice }